### ISSUE TITLE
systemd-formula don't create the service file in target system

### ISSUE THREAD

**Issue by MurzNN** [saltstack-formulas/systemd-formula#63]
I have created this Pillar file, based on https://github.com/saltstack-formulas/systemd-formula/blob/master/pillar.example:
```
systemd:
  service:
    test:
      enabled: true
      status: running
      Unit:
        Description: Test service
        After: network.target

      Service:
        ExecStart: osrm-routed /home/brick-osm/osrm-data/RU.osrm
        WorkingDirectory: /home/brick-osm/osrm-data
        User: brick-osm
        Group: brick-osm

      Install:
        WantedBy: multi-user.target
```
It's included successfully when applying configuration, and produce no errors. But as result, no service is created on target minion. Can you please help to find, where is can be the problem?

Maybe I need to add some additional required parameter to yaml for make this works? Or maybe move the service configuration to 'systemd.units' group?

OS: Ubuntu 20.04, Solr 3002.2+ds-1
